project_id = "pecotcxpcqfkwvyylvjv"

[db]
password = { env = "SUPABASE_DB_PASSWORD" }

[functions.stripe-webhook]
verify_jwt = false



[functions.verify-checkout-session]
verify_jwt = false

[auth]
enabled = true
site_url = "https://www.tickrace.com"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[functions.admin-stats]
verify_jwt = false

[functions.admin-ca]
verify_jwt = false

[functions.set-admin]
verify_jwt = false

[functions.admin-courses-kpis]
verify_jwt = false

[functions.cors-ping]
verify_jwt = false