// src/config/sports.js
import {
  Mountain,
  Route,
  Bike,
  Flag,
  Waves,
  Snowflake,
  Compass,
  Shield,
  PawPrint,
  Timer,
} from "lucide-react";

export const SPORTS = [
  {
    code: "trail",
    label: "Trail",
    icon: Mountain,
    defaultTimingMode: "splits",
    show: { distance: true, dplus: true, gpx: true },
  },
  {
    code: "running",
    label: "Running / Route",
    icon: Route,
    defaultTimingMode: "simple",
    show: { distance: true, dplus: false, gpx: false },
    disciplines: [
      { code: "5k", label: "5 km" },
      { code: "10k", label: "10 km" },
      { code: "hm", label: "Semi-marathon" },
      { code: "marathon", label: "Marathon" },
      { code: "track", label: "Piste" },
      { code: "cross", label: "Cross" },
    ],
  },
  {
    code: "hiking",
    label: "Rando / Marche",
    icon: Flag,
    defaultTimingMode: "simple",
    show: { distance: true, dplus: true, gpx: true },
    disciplines: [
      { code: "rando_chrono", label: "Rando chronométrée" },
      { code: "marche_nordique", label: "Marche nordique" },
    ],
  },
  {
    code: "mtb",
    label: "VTT",
    icon: Bike,
    defaultTimingMode: "splits",
    show: { distance: true, dplus: true, gpx: true },
    disciplines: [
      { code: "xc", label: "XC" },
      { code: "marathon", label: "Marathon VTT" },
      { code: "enduro", label: "Enduro (spéciales)" },
      { code: "ebike", label: "E-bike" },
    ],
  },
  {
    code: "gravel",
    label: "Gravel",
    icon: Bike,
    defaultTimingMode: "simple",
    show: { distance: true, dplus: true, gpx: true },
  },
  {
    code: "cycling_road",
    label: "Cyclosportive / Route",
    icon: Bike,
    defaultTimingMode: "simple",
    show: { distance: true, dplus: true, gpx: true },
    disciplines: [
      { code: "cyclosportive", label: "Cyclosportive" },
      { code: "tt", label: "Contre-la-montre" },
    ],
  },
  {
    code: "triathlon",
    label: "Triathlon",
    icon: Timer,
    defaultTimingMode: "waves",
    show: { distance: true, dplus: false, gpx: false },
    disciplines: [
      { code: "sprint", label: "Sprint" },
      { code: "olympic", label: "Olympique" },
      { code: "md", label: "M" },
      { code: "ld", label: "L" },
      { code: "xtri", label: "XTri" },
    ],
  },
  {
    code: "swimrun",
    label: "Swimrun",
    icon: Waves,
    defaultTimingMode: "relay",
    show: { distance: true, dplus: false, gpx: true },
  },
  {
    code: "raid_multisport",
    label: "Raid multisport",
    icon: Shield,
    defaultTimingMode: "stages",
    show: { distance: false, dplus: false, gpx: true },
  },
  {
    code: "orienteering",
    label: "Course d’orientation",
    icon: Compass,
    defaultTimingMode: "penalties",
    show: { distance: false, dplus: false, gpx: false },
  },
  {
    code: "winter",
    label: "Neige / Hiver",
    icon: Snowflake,
    defaultTimingMode: "splits",
    show: { distance: true, dplus: true, gpx: false },
    disciplines: [
      { code: "skimo", label: "Ski-alpinisme" },
      { code: "xc_ski", label: "Ski de fond" },
      { code: "snowshoe", label: "Raquettes" },
      { code: "snow_trail", label: "Trail blanc" },
    ],
  },
  {
    code: "ocr",
    label: "Course à obstacles",
    icon: Shield,
    defaultTimingMode: "penalties",
    show: { distance: true, dplus: false, gpx: false },
  },
  {
    code: "canisport",
    label: "Canisport",
    icon: PawPrint,
    defaultTimingMode: "simple",
    show: { distance: true, dplus: true, gpx: true },
    disciplines: [
      { code: "canicross", label: "Canicross" },
      { code: "canivtt", label: "CaniVTT" },
      { code: "canitrott", label: "Canitrott" },
    ],
  },
];
